[package]
name = "iris_classification_tchrs"
version = "0.1.0"
authors = ["Joydeep Bhattacharjee <joydeepubuntu@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
serde = "1.0.89"
serde_derive = "1.0.89"
rand = "0.6"
tch = "0.0.6"
ml-utils = { path = "../ml-utils" }