[package]
name = "nb_classification"
version = "0.1.0"
authors = ["Joydeep Bhattacharjee <joydeepubuntu@gmail.com>"]
edition = "2018"

[dependencies]
csv = "*"
rusty-machine="*"
hyper = "*"
rulinalg = { version = "0.4.2", features = ["io"] }
serde = "1"
serde_derive = "1"
rand = "0.6.5"